service: helloTest
provider:
  name: aws
  runtime: nodejs6.10
functions:
  hello:
    handler: index.handler
    events:
      - http:
          path: helloTest
          method: get
      - http:
          path: helloTest
          method: post
