AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Jest serverless application.

Resources:

  Products:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      Timeout: 30
      Events:
        GetForm:
          Type: Api
          Properties:
            Path: /helloTest
            Method: get
        ExecuteTests:
          Type: Api
          Properties:
            Path: /dev/helloTest
            Method: post